### ISSUE TITLE
When will the latest 4.x version be released?

### ISSUE THREAD

**Issue by crazyyanchao** [GraphFoundation/ongdb#26]

**Comment by bradnussbaum** [comment]
Hi @crazyyanchao - 4.x is being worked on and is planned after the current 3.6 release. The 3.6 release contains important features to the community that are needed prior to 4.0.

The highest priority features of 4.0 is multi-database support. There is currently no timeline set for the 4.0 release. The 3.6 release is scheduled for mid to late April.

Hope that helps.
