### ISSUE TITLE
query logging is not working on enterprise 

### ISSUE THREAD

**Issue by ghost** [GraphFoundation/ongdb#4]
- Neo4j version: 3.5.4
- Operating system: Ubuntu 16.04
- API/Driver: none
- **Steps to reproduce**
- Expected behavior : query.log file collect the logs, with configuration of enabling query.log. set true (on conf/neo4j.conf)
- Actual behavior: not collecting any query, the file size of query.log is always 0

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

### Steps to reproduce
1. download tarball on https://www.graphfoundation.org/projects/ongdb/
- file name: ongdb-enterprise-3.5.4-unix.tar.gz
2. set enable query logging on file, "conf/neo4j.conf" (remove '#' query.log~~= )
3. start neo4j

Note: Compare to enterprise, 1 month trial version of neo4j,
it works with same steps above.
Note: I tried this with all version of 3.4.0 source code, with maven compile, and run it but, ongDB enterprise version does not collect query.log.
"query.log" is only activated on enterprise model on neo4j.

### Expected behavior
`logs/query.log` should be collecting the logs and changing of file size

### Actual behavior
`logs/query.log` file size always 0.

**Comment by bradnussbaum** [comment]
@sumin-lim Thanks for reporting this. We're taking a look.

**Comment by jmsuhy** [comment]
I will verify the issue also exists in 3.5.6-SNAPSHOT as well so we can pinpoint the issue and fix it.

**Comment by jmsuhy** [comment]
I tested in 3.5.3, 3.5.4 and 3.5.9-SNAPSHOT and it works fine.   I suspect you did not set query.threshold to zero to log all queries.  See the instructions below.

dbms.logs.query.enabled=true
dbms.logs.query.threshold=0

https://neo4j.com/docs/operations-manual/current/monitoring/logging/query-logging/
