### ISSUE TITLE
Invoke-Neo4j : Unable to determine the version of the installation

### ISSUE THREAD

**Issue by huanbd** [GraphFoundation/ongdb#41]
I've get an error when start db use command `bin\neo4j start`
```
Invoke-Neo4j : Unable to determine the version of the installation at F:\ONgDB\ongdb-enterprise-3.6.0.RC1
At F:\ONgDB\ongdb-enterprise-3.6.0.RC1\bin\neo4j.ps1:29 char:7
+ Exit (Invoke-Neo4j -Verbose:$Arguments.Verbose -Command $Arguments.Ar ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j
```
**ONgDB Version:** 3.6 RC1
**Operating System:** Window 10

Note: When I change to use version 3.5.17, run with that command, and not get error like that, it run perfect

**Comment by bradnussbaum** [comment]
Hi @huanbd,

We are looking into this issue and expect to have it resolved shortly.

Best,
Brad

**Comment by jmsuhy** [comment]
I just committed a fix for this issue.  Will generate a PR.

**Comment by huanbd** [comment]
Thank you, @jmsuhy !

**Comment by bradnussbaum** [comment]
PR with fix is building here: https://github.com/graphfoundation/ongdb/pull/43

This will go out in the 3.6.0 release.
