### ISSUE TITLE
version 4.0 release date

### ISSUE THREAD

**Issue by xilong-d** [GraphFoundation/ongdb#51]
is there any plan to release version 4.0 for ongdb

**Comment by bradnussbaum** [comment]
@xilong-d Yes - 4.0 development is in progress. We are working on the new Causal Clustering support. Multi-db support is already in.

**Comment by xilong-d** [comment]
Thanks for you promptly reply. So we can use multi-db in 3.6 version now. Is it correct?

**Comment by bradnussbaum** [comment]
@xilong-d Multi-db will not be available until the 4.0 release. It is not in the 3.6 release. We currently have multi-db support working in the 4.0 branch and we need to finish Casual Clustering before we can make the 4.0 release.
