### ISSUE TITLE
Support for neosemantics

### ISSUE THREAD

**Issue by yvrohith** [GraphFoundation/ongdb#53]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.
If you have questions on how to use ONgDB, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

## Feature request template

**Is your feature request related to a problem? Please describe.**
Looks like [neosemantics](https://github.com/neo4j-labs/neosemantics) (n10s) is not yet supported on the latest version of OngDB (version 3.6). 

**Describe the solution you'd like**
Please consider implementing support for n10s in a future release of OngDB

**Comment by giantamoeba** [comment]
I am using neosemantics-3.5.0.4.jar with ongdb 3.6 without any problems
