### ISSUE TITLE
About ONGDB new data storage slow problem

### ISSUE THREAD

**Issue by Wangdaen** [GraphFoundation/ongdb#62]
In the process of data insertion, when the amount of data increases to millions, the problem of slow entry of new data will occur. Whether it is in a single machine or in a cluster mode, the data will be added too slowly, and the insertion problem will occur about once every 3 seconds.
It could be a relationship where I put a unique constraint on the data.
It's not clear exactly what caused it.

**Comment by Wangdaen** [comment]
@michaelklishin

**Comment by alexiudice** [comment]
Could you give more context about your issue? There are a few different ways to import data into an ONgDB database and to help you we need to know how you are inserting your data. Providing the specific cypher query you are using to load in data would be very helpful.

**Comment by alexiudice** [comment]
Closing this issue after author has not responded in two weeks. If you are still having problems with this please re-open an Issue with more details.
