### ISSUE TITLE
Understanding why ONgDB uses AGPLv3

### ISSUE THREAD

**Issue by rikonor** [GraphFoundation/ongdb#63]
Hi,

I was wondering why does ONgDB use AGPLv3 for its enterprise features. Is it because the code it originated from (i.e Neo4j's enterprise code) was AGPLv3?

Thanks!

**Comment by bradnussbaum** [comment]
Hi @rikonor - Yes that's exactly the reason. Neo4j enterprise code is licensed under AGPLv3 and community code is licensed under GPLv3. For the versions of ONgDB where we are using that code we need are continuing to release under those same licenses.

**Comment by rikonor** [comment]
Thanks for the quick response and explanation @bradnussbaum. That makes sense.
