### ISSUE TITLE
A query guard like this would be a good feature to add at some point. - Slack Feature Request

### ISSUE THREAD

**Issue by crazyyanchao** [GraphFoundation/ongdb#64]
- Tony Ma Jan 14th at 9:11 AM
```
How do I disable certain queries?And available for all non-administrator accounts? eg. I have to disable this query.  MATCH (n) DELETE n
```
- bradnussbaum  
```
I believe this can be done with a procedure that uses a pre-commit hook.
```
- bradnussbaum  
```
But would need to be written custom.
```
- bradnussbaum  
```
A query guard like this would be a good feature to add at some point.
```
- Tony Ma  
```
Yes,It would be great to upgrade a smaller version(eg.3.5.23) and add this feature.
```

**Comment by alexiudice** [comment]
The quick and dirty way to accomplish this would be to follow Brad's advice and add some custom Java code that looks at the query and matches it against a hard-coded list of banned queries.  Unfortunately, using it in this manner would require a code change in the first place, so I don't think this solution is something we'd add to the main ONgDB code. You could clone the ONgDB code and make the changes yourself and build your own stand-alone of ONgDB.  


A more user-friendly version of this feature would be something like disabling/enabling specific queries through a procedure. I don't think that would be worth the time adding. That would take a lot of work and it would not be an easy thing to do due. I'm pretty sure it would require editing ONgDB internal store classes to keep track of queries disabled after restarts/migrations.
