### ISSUE TITLE
ONgDB clustering (Neo4j fork?)

### ISSUE THREAD

**Issue by faiz-usmani** [GraphFoundation/ongdb#65]
Hi. 

We are setting up an ONgDB cluster for high performance. Two questions arise here - 
a. Is release 3.6.2 a candidate that is recommended or should we stick with 3.5.22 LTS instead. 
b. When setting up clustering, which set of instructions should be followed from Neo4j operation guides, i.e. 3.x or 4.x set of instructions, since the settings are different for the two.  The answer (probably) would be influenced by the Neo4j version the forks are from. Would you recommend following the Neo4j 3.5 set of instructions for the same (https://neo4j.com/docs/operations-manual/3.5/clustering/introduction/#causal-clustering-introduction-operational), or 4.x ? 
We are open to using versions 3.6.2 or 3.5.22: Though 3.5.22 is certainly LTS. 

Advice on this matter is highly appreciated. 

Kind regards

**Comment by alexiudice** [comment]
@faiz-usmani Hello!

The 3.6.x changes center around Fulltext indexes. If you don't need those additional features I would recommend using 3.5.22 LTS for now. 

I would also recommend using the 3.5 operation guide you've linked in your post. 

Please let me know if you have any other questions.

**Comment by faiz-usmani** [comment]
Many thanks @alexiudice. 
This does help the cause my end. 

The one bit missing for me is around the cadence of 'forks' from Neo4j. 
Was it the initial fork from Neo4j in 2017 and the journey so far has been incremental; I believe that is the case. 
It would be fair to assume that we have not had any other forks off Neo4j.

**Comment by alexiudice** [comment]
@faiz-usmani ONgDB is a dedicated fully open source fork of Neo4j. Different ONgDB versions (3.5, 3.6, and upcoming 4.x) are managed by distinct branches, but all work is under this same fork. 

Please see https://www.graphfoundation.org/  for more details and join our community slack `graphfoundation.slack.com
`
