### ISSUE TITLE
'Tried to copy more data into less' bug fixed in 3.5.4 is now back in 3.5.14

### ISSUE THREAD

**Issue by DelphinePrinet** [GraphFoundation/ongdb#66]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

To help us understand your issue, please specify important details, primarily:

- ONgDB version: 3.5.14
- Operating system: Mac Big Sur 11.1

- **Steps to reproduce**
Ran a query (in the browser) that works fine in Neo Enterprise v. 3.5.19, as well as with ONgDB 3.5.4, 3.5.11 and 3.5.12.  However when I try with 3.5.14, I get the error message. The query contains a line with pattern comprehension, which seems to cause the issue:
return head([(c)-[:HAS_GROUP]->(g) | g.GRP_LONG]) as Subarea

![image](https://user-images.githubusercontent.com/34459386/106188017-a6060100-6163-11eb-8e59-ae544d27043e.png)

**Comment by DelphinePrinet** [comment]
Hello,

I noticed that this issue is now closed; does that mean that the fix will be in the next release of ONgDB?

Thank you

Delphine

**Comment by bradnussbaum** [comment]
@DelphinePrinet Unfortunately we will no longer be able to support ONgDB 3.5. Please see the official statement with more details: https://www.graphfoundation.org/graph-foundation-resolution-for-future-ongdb-development/

**Comment by DelphinePrinet** [comment]
Thank you for the update
