### ISSUE TITLE
Dockerhub images and tags for ongdb project

### ISSUE THREAD

**Issue by godois** [GraphFoundation/ongdb#68]
Hi guys, 

All tags and images of ongdb is not available at dockerhub.com. Any idea what's happened?

Currently it´s not possible to run any container

Thanks

**Comment by bradnussbaum** [comment]
@godois Please see official statement: https://www.graphfoundation.org/graph-foundation-resolution-for-future-ongdb-development/

Per resolution we are removing support for post ONgDB 3.4, 3.5 and 3.6 versions and will be releasing ONgDB 1.0 in the coming days.

**Comment by jmsuhy** [comment]
You can use GraphStack.io packages that are built by the GraphStack.io team for the open source graph community.   
See https://graphstack.io -> The docker hub coordinates can be found in the Downloads section.   
Note: We are not endorsed or sponsored by Neo4j or Graph Foundation - if you have any issues - you can use the GraphStack.io Github page (https://github.com/graphstackio/ongdb-legacy-3.x/)  to file issues or request specific versions be packaged.
