### ISSUE TITLE
Cypher query returns error in 3.5.19 , 3.5.22 and 3.5.26 while it was running in 3.5.4

### ISSUE THREAD

**Issue by graphileon** [GraphFoundation/ongdb#70]
this query

```
MATCH (n1)<--(n2)-->(n3)
WHERE n1 <> n3
WITH n2 limit 1
RETURN [(n2)-->(m) | id(m)][0]
```
returns an error on 3.5.19 , 3.5.22 and 3.5.26  while on 3.5.4 it returns an id.
![image](https://user-images.githubusercontent.com/65026869/110478771-5d8c1c80-80ed-11eb-8d6a-fa6050a2d217.png)

Without the array index at the end, it runs well and returns the expected array of ids.
```
MATCH (n1)<--(n2)-->(n3)
WHERE n1 <> n3
WITH n2 limit 1
RETURN [(n2)-->(m) | id(m)]
```

FYI.. the corresponding Neo4j versions do not seem to suffer from this issue.

**Comment by graphileon** [comment]
the issue seems to be related to the CYPHER version.  When prefixing with `CYPHER 3.4`, the issue does not appear. With `CYPHER 3.5` the error appears.

```
CYPHER 3.4
MATCH (n1)<--(n2)-->(n3)
WHERE n1 <> n3
WITH n2 limit 1
RETURN [(n2)-->(m) | id(m)][0] 
```

**Comment by jmsuhy** [comment]
FYI: I am working on fixing this on the GraphStack fork.   https://github.com/graphstackio/
I am subscribed to this project and saw your issue so I wanted to let you know.   The GraphFoundation is not supporting 3.5 anymore.  I am not part of the foundation, just an open source advocate and committer.
