### ISSUE TITLE
ONgDB 3.5.22 and 3.6.2 Docker Images on Docker Hub. 

### ISSUE THREAD

**Issue by faiz-usmani** [GraphFoundation/ongdb#71]
**ONgDB 3.5.22 and 3.6.2 Docker images on Docker Hub**. 

Could you please point me to the location to download Docker images for versions 3.5.22 and 3.6.2 please? 
The docker images for the versions stated above were available at hub.docker.com . 
I only see images tagged 1.0 and 1.0.0-alpha. (https://hub.docker.com/r/graphfoundation/ongdb/tags?page=1&ordering=last_updated)

These updates have of course been uploaded in the last 12 hours. Can you please confirm what is the status of the docker images for 3.6.2 and 3.5.22 please and where can these be found and downloaded.  
We are a bit stuck in our progress and actually re-thinking our strategy on graph databases and any help will be much appreciated. 

Regards 
Faiz Usmani 
(Architect and Dev @Nymi)

**Comment by bradnussbaum** [comment]
See #68 for details.
