### ISSUE TITLE
Questions in terms of enterprise version

### ISSUE THREAD

**Issue by suesunss** [GraphFoundation/ongdb#8]
Hi,

Thanks for having ongdb.

In terms of enterprise version, I have a question. As far as I know, neo4j has deleted the 'enterprise' code base starting from 3.5, whereas ongdb still maintains the 'enterprise' part, does it merge from the official neo4j code base prior to 3.5 ? Will ongdb adds new features to this part in the future ? (I am not diving into the code details yet, sorry for a quick ask)

**Comment by bradnussbaum** [comment]
Hi @suesunss,

You are correct, the neo4j enterprise code was removed from the neo4j project repository as of 3.5 when Neo4j Inc. changed to an Open Core model. You can read more about that transition here: https://www.graphfoundation.org/neo4j-is-open-core-now-what-ujah7ein5mis/.

The Open Native Graph Database (ONgDB) Project maintains and advances feature development of all the current enterprise features plus more to come in the future. ONgDB is developed by the open source community under The Graph Foundation which is a non-profit with 501(c)(3) status. The Graph Foundation functions similar to the Linux/Apache/Free Software Foundations and provides all software distributions for free at no cost.

Like other open source projects with similar models we rely on contributions from the community to advance development and sponsorship to fund operational costs. The Graph Foundation was started by community members that had formerly been developing in the neo4j community and continue now on a mission to move open source efforts forward.

Hope that helps and happy to answer any other questions.

Thanks,
Brad

**Comment by suesunss** [comment]
@bradnussbaum 
Sounds great ! 
I will try to dive into this project now.
