### ISSUE TITLE
Upstream version of OngDB

### ISSUE THREAD

**Issue by jgupta** [GraphFoundation/ongdb#94]
What upstream version is ongdb based on? In browser dashboard under DBMS it says version 3.4.0.

If this is actually based on version 3.4.0 then why versions of 3.5/3.6 has been removed?

I am asking this because we are encountering [a bug](https://github.com/graphfoundation/ongdb/issues/93) that was not in 3.5.

**Comment by jsoref** [comment]
There's an "About" section on https://github.com/graphfoundation/ongdb which says:

> ONgDB is an independent fork of Neo4j® Enterprise Edition version 3.4.0.rc02 licensed under AGPLv3 and/or Community Edition licensed under GPLv3

**Comment by crazyyanchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jsoref** [comment]
It's also covered in https://github.com/graphfoundation/ongdb/blob/1.0/README.asciidoc#unaffiliated-with-neo4j-inc
